default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 
development:
  <<: *default
  database: blogapp
  host: localhost
  username: postgres
  password: 1234.com


test:
  <<: *default
  database: blogapp_test
  username: postgres
  password: 1234.com

production:
  <<: *default
  database: blogapp
  username: postgres
  password: 1234.com